package com.cyb.blogserver.dao;

import com.cyb.blogserver.domain.User;

import java.util.List;
import java.util.Set;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 24 22:47:16 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 24 22:47:16 CST 2019
     */
    int insert(User record);

    int updateByPrimaryKey(User record);

	Set<String> queryRolesByName(String userName);

	Set<String> queryPermissionByName(String userName);

    List<User> selectByUserName(String name);

    User selectByPrimaryKey(String id);
}