package com.cyb.blogserver.domain;

public class Parames {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.id
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.name
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.value
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parames.remark
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.id
     *
     * @return the value of parames.id
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.id
     *
     * @param id the value for parames.id
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.name
     *
     * @return the value of parames.name
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.name
     *
     * @param name the value for parames.name
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.value
     *
     * @return the value of parames.value
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.value
     *
     * @param value the value for parames.value
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parames.remark
     *
     * @return the value of parames.remark
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parames.remark
     *
     * @param remark the value for parames.remark
     *
     * @mbg.generated Thu Feb 14 14:51:17 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}