package com.cyb.blogserver.domain;

import java.util.ArrayList;
import java.util.List;

public class UserRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    protected List<UserRoleCriteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public UserRoleExample() {
        oredCriteria = new ArrayList<UserRoleCriteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public List<UserRoleCriteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public void or(UserRoleCriteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public UserRoleCriteria or() {
        UserRoleCriteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public UserRoleCriteria createCriteria() {
        UserRoleCriteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    protected UserRoleCriteria createCriteriaInternal() {
        UserRoleCriteria criteria = new UserRoleCriteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public UserRoleCriteria andIdIsNull() {
            addCriterion("id is null");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdEqualTo(String value) {
            addCriterion("role_id =", value, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdNotEqualTo(String value) {
            addCriterion("role_id <>", value, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdGreaterThan(String value) {
            addCriterion("role_id >", value, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_id >=", value, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdLessThan(String value) {
            addCriterion("role_id <", value, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdLessThanOrEqualTo(String value) {
            addCriterion("role_id <=", value, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdLike(String value) {
            addCriterion("role_id like", value, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdNotLike(String value) {
            addCriterion("role_id not like", value, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdIn(List<String> values) {
            addCriterion("role_id in", values, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdNotIn(List<String> values) {
            addCriterion("role_id not in", values, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdBetween(String value1, String value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRoleIdNotBetween(String value1, String value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (UserRoleCriteria) this;
        }

        public UserRoleCriteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (UserRoleCriteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_role
     *
     * @mbg.generated do_not_delete_during_merge Sat May 04 15:10:29 CST 2019
     */
    public static class UserRoleCriteria extends GeneratedCriteria {

        protected UserRoleCriteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}