package com.cyb.blogserver.service;

import com.cyb.blogserver.domain.UserRole;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleServices {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    UserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 04 15:10:29 CST 2019
     */
    int updateByPrimaryKey(UserRole record);

    List<UserRole> selectByUserId(String id);
}